name: Setup
description: Setup repository
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
        cache: pip
    - run: pip install -r requirements.txt
